### ISSUE TITLE
Re-enabling re-rendering bot

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-maintenance#4]
I think many of the re-rendering issues that existed before were issues with `conda-smithy`, `conda-build-all`, or `conda-build` that have been fixed. Was trying some of the problem cases over the last few days and was not able to reproduce them. The last issue I saw was the AppVeyor badge, which we fixed. Would it be possible to turn back on the re-rendering PRs? It would be nice to get things back up to date in a scalable manner.

**Comment by pelson** [comment]
Re-rendering now re-enabled nightly with:

```
conda execute -fv \
    https://raw.githubusercontent.com/conda-forge/conda-forge.github.io/master/scripts/regenerate_feedstock.py \
        --feedstocks-dir feedstocks --limit 5
```

Similarly, I have updated the pinning script to:

```
conda execute -fv \
    https://raw.githubusercontent.com/conda-forge/conda-forge.github.io/master/scripts/pin_the_slow_way.py \
        --feedstocks-dir feedstocks --limit 20
```

i.e. the script in conda-forge/conda-forge.github.io is _live_ and merges result in immediate changes to the bot. 🎉 

For the record, I needed to release conda-smithy 1.1.2 so that the rerendering didn't incorrectly pick up the wrong package index and conclude that there were unresolvable cases (e.g. https://github.com/conda-forge/conda-smithy/pull/274).

**Comment by jakirkham** [comment]
Super excited about this. Thanks so much @pelson.

**Comment by pelson** [comment]
My pleasure. Glad to have the bot back.
